#!/bin/bash

DB_SOURCE_HOST=""
DB_SOURCE_USER=""
DB_SOURCE_PASS=""
DB_SOURCE_DB_NAME=""

DB_DES_HOST=""
DB_DES_USER=""
DB_DES_PASS=""
DB_DES_DB_NAME=""

echo -n "Enter DB_SOURCE_HOST: "
read DB_SOURCE_HOST
echo -n "Enter DB_SOURCE_USER: "
read DB_SOURCE_USER
echo -n "Enter DB_SOURCE_PASS: "
read DB_SOURCE_PASS
echo -n "Enter DB_SOURCE_DB_NAME: "
read DB_SOURCE_DB_NAME
